//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.EmsLeadEngine.Core.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.13.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Endpoint=sb://eddysbntest.servicebus.windows.net/;SharedAccessKeyName=RootManageS" +
            "haredAccessKey;SharedAccessKey=2x7gSwKi3rees9waXBcHaYkr4EAJYP6movHGgudWyog=")]
        public string ServiceBusConnectionString {
            get {
                return ((string)(this["ServiceBusConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sfleadcreate")]
        public string InsertQueueName {
            get {
                return ((string)(this["InsertQueueName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sfleadupdate")]
        public string UpdateQueueName {
            get {
                return ((string)(this["UpdateQueueName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseSalesforceSandbox {
            get {
                return ((bool)(this["UseSalesforceSandbox"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LogInformationMessages {
            get {
                return ((bool)(this["LogInformationMessages"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int CacheRefreshMinutes {
            get {
                return ((int)(this["CacheRefreshMinutes"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DefaultEndpointsProtocol=https;AccountName=joneddysa;AccountKey=gVkotDbEcNRQX5i7N" +
            "L/Y1nuUVC9x+ZnNh8YbHaZwm8vKcMzYY0qRqrRXTXiOPDLcDfP1E/9rCpz8HZsU+pf5Kg==;Endpoint" +
            "Suffix=core.windows.net")]
        public string FBConversionConnection {
            get {
                return ((string)(this["FBConversionConnection"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("fbconversionapi")]
        public string FBConversionQueueName {
            get {
                return ((string)(this["FBConversionQueueName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("fbaudience")]
        public string FBAudienceQueueName {
            get {
                return ((string)(this["FBAudienceQueueName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/SXX84GHsauvghL6T0/uJLfpmuk+Lg367JFr61vHzWw=")]
        public string EventGridTopicKey {
            get {
                return ((string)(this["EventGridTopicKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("googleconversionapi")]
        public string GoogleConversionQueueName {
            get {
                return ((string)(this["GoogleConversionQueueName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DefaultEndpointsProtocol=https;AccountName=saeddygooconvapidev;AccountKey=TOmGf9g" +
            "Q4SgJ4s/jXXqy73gWP+fLm1T/zLP8lyGAEtJf65+L5pMhbOTeods+zGyVGpHYVfWPWZmDzwqq+tLo9w=" +
            "=;EndpointSuffix=core.windows.net")]
        public string GoogleConversionConnection {
            get {
                return ((string)(this["GoogleConversionConnection"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("gooaudiencedev")]
        public string GoogleAudienceQueueName {
            get {
                return ((string)(this["GoogleAudienceQueueName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DefaultEndpointsProtocol=https;AccountName=saeddygooconvapidev;AccountKey=TOmGf9g" +
            "Q4SgJ4s/jXXqy73gWP+fLm1T/zLP8lyGAEtJf65+L5pMhbOTeods+zGyVGpHYVfWPWZmDzwqq+tLo9w=" +
            "=;EndpointSuffix=core.windows.net")]
        public string GoogleAudienceConnection {
            get {
                return ((string)(this["GoogleAudienceConnection"]));
            }
        }
    }
}
